env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2020
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - off
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-duplicate-imports:
    - error
